# Generated by Django 2.1.1 on 2019-11-02 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_agentmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstats',
            name='average_online_time',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='agentstats',
            name='cases_per_hour',
            field=models.FloatField(null=True),
        ),
    ]
