# Generated by Django 2.1.1 on 2019-11-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20191102_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentstats',
            name='csat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='agentstats',
            name='emails_sent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='agentstats',
            name='survey_take_rate',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='agentstats',
            name='surveys_taken',
            field=models.IntegerField(null=True),
        ),
    ]
