# Generated by Django 2.1.1 on 2019-11-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_auto_20191102_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manager', models.CharField(max_length=50)),
                ('cases_worked', models.IntegerField(null=True)),
                ('days_worked', models.IntegerField(null=True)),
                ('cases_per_day', models.FloatField(null=True)),
                ('average_online_time', models.FloatField(null=True)),
                ('cases_per_hour', models.FloatField(null=True)),
                ('csat', models.FloatField(null=True)),
                ('surveys_taken', models.IntegerField(null=True)),
                ('emails_sent', models.IntegerField(null=True)),
                ('survey_take_rate', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
