# Generated by Django 2.1.1 on 2019-11-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_managerstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerstats',
            name='name',
        ),
    ]
